project:
  type: website

website:
  title: "Playing with LLM prompts"
  navbar:
    right:
      - about.qmd
      - icon:
      - text: 
format:
  html:
    theme: morph
    css: styles.css

execute:
  freeze: auto


